apiVersion: batch/v1
kind: CronJob
metadata:
  name: caddy-cronjob
  namespace: caddy
spec:
  schedule: "0/30 * * * *" # Runs every 30m
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dns-caddy
              image: wilgrimthepilgrim/caddy:0.3
          restartPolicy: OnFailure
