apiVersion: batch/v1
kind: CronJob
metadata:
  name: caddy-cronjob
  namespace: caddy
spec:
  schedule: "1/2 * * * *" # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dns-caddy
              image: 247004601951.dkr.ecr.us-west-2.amazonaws.com/dns-caddy:latest
              envFrom:
              - secretRef:
                  name: caddy-secret
          restartPolicy: OnFailure
