apiVersion: batch/v1
kind: CronJob
metadata:
  name: caddy-cronjob
  namespace: caddy
spec:
  schedule: "1/2 * * * *" # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dns-caddy
              image: wilgrimthepilgrim/caddy:0.1
              envFrom:
              - secretRef:
                  name: caddy-secret
          restartPolicy: OnFailure
