apiVersion: v1
kind: Secret
metadata:
  name: caddy-secret
  namespace: caddy
  labels:
    app: caddy
type: Opaque
data:
  CLOUDFLARE_API_TOKEN: dGVzdGZpZWxkCg==
  CLOUDFLARE_ZONE_NAME: dGVzdGZpZWxkCg==
  CLOUDFLARE_RECORD_NAME: dGVzdGZpZWxkCg==
